version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: jewels/catalogapi
    build:
      context: ./ProductCatalogAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source = mssqlserver; Initial Catalog = CatalogDb; User Id=sa;Password=ProductApi123(!); Connect Timeout = 30; Encrypt = False; Trust Server Certificate=False; "
      ExternalBaseUrl: "http://localhost:7000"
    ports:
      - "7000:8080"
    container_name: jewelscatalogapi
    networks:
      - frontend
      - backend
    depends_on:
      - mssqlserver

  webmvc:
    image: jewels/webmvc
    build:
      context: ./WebMVC
      dockerfile: Dockerfile
    environment:
      CatalogUrl: http://localhost:7000
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "7500:8080"
    container_name: webshop
    networks:
      - frontend
    depends_on:
      - catalog

  mssqlserver:
    image: "mcr.microsoft.com/mssql/server:2022-latest"  
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: ProductApi123(!)
    ports:
      - "1448:1433"
    container_name: jewelscatalogsqlserver
    networks:
      - backend