version: '3.4'

networks:
  frontend:
  backend:

services:
  catalog:
    image: jewels/catalogapi
    build:
      context: ./ProductCatalogAPI
      dockerfile: Dockerfile
    environment:
      ConnectionString: "Data Source = (localdb)\\MSSQLLocalDB; Initial Catalog = CatalogDb; Integrated Security = True; Connect Timeout = 30; Encrypt = False; Trust Server Certificate=False; "
      ExternalBaseUrl: "https://localhost:7106"
    ports:
      - "7000:80"
    container_name: jewelscatalogapi
    networks:
      - frontend
      - backend